python sameChunk.py
sleep 5m
python randomChunks.py
sleep 5m
python partialPlane.py
exit(9)
#sleep 3h
#python sameChunk.py
#sleep 5m
#python randomChunks.py
#sleep 5m
#python partialPlane.py
#sleep 3h
#python sameChunk.py
#sleep 5m
#python randomChunks.py
#sleep 5m
#python partialPlane.py
#sleep 3h
#python sameChunk.py
#sleep 5m
#python randomChunks.py
#sleep 5m
#python partialPlane.py
#sleep 3h
python sameChunk.py
sleep 5m
python randomChunks.py
sleep 5m
python partialPlane.py
sleep 3h
python sameChunk.py
sleep 5m
python randomChunks.py
sleep 5m
python partialPlane.py
sleep 3h
python sameChunk.py
sleep 5m
python randomChunks.py
sleep 5m
python partialPlane.py
sleep 3h
python sameChunk.py
sleep 5m
python randomChunks.py
sleep 5m
python partialPlane.py
sleep 3h
python sameChunk.py
sleep 5m
python randomChunks.py
sleep 5m
python partialPlane.py
sleep 3h
python sameChunk.py
sleep 5m
python randomChunks.py
sleep 5m
python partialPlane.py
